// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8_RIo3N8GDoBBufmZFqq0EWaZPFzZzmw',
    appId: '1:860802954200:web:95f33ee4e7ec97992638ad',
    messagingSenderId: '860802954200',
    databaseURL: 'https://flutteratividade4-default-rtdb.firebaseio.com/',
    projectId: 'flutteratividade4',
    authDomain: 'flutteratividade4.firebaseapp.com',
    storageBucket: 'flutteratividade4.firebasestorage.app',
    measurementId: 'G-SJE1MPQQS5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCox7zG3rdulT4rFiZdrZMc_ex8UaIReF4',
    appId: '1:860802954200:android:975aff33a9e040e42638ad',
    messagingSenderId: '860802954200',
    projectId: 'flutteratividade4',
    storageBucket: 'flutteratividade4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvHoqhEfLUKcsP5ovIdkEuKv4I7ezV5A0',
    appId: '1:860802954200:ios:4b1bb8241c8d41e32638ad',
    messagingSenderId: '860802954200',
    projectId: 'flutteratividade4',
    storageBucket: 'flutteratividade4.firebasestorage.app',
    iosBundleId: 'com.example.atvdnova',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvHoqhEfLUKcsP5ovIdkEuKv4I7ezV5A0',
    appId: '1:860802954200:ios:4b1bb8241c8d41e32638ad',
    messagingSenderId: '860802954200',
    projectId: 'flutteratividade4',
    storageBucket: 'flutteratividade4.firebasestorage.app',
    iosBundleId: 'com.example.atvdnova',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8_RIo3N8GDoBBufmZFqq0EWaZPFzZzmw',
    appId: '1:860802954200:web:95de07f769c8fae22638ad',
    messagingSenderId: '860802954200',
    projectId: 'flutteratividade4',
    authDomain: 'flutteratividade4.firebaseapp.com',
    storageBucket: 'flutteratividade4.firebasestorage.app',
    measurementId: 'G-E4XNV2MS80',
  );

}